### ISSUE TITLE
Test failure in func_taskfeature_test.py

### ISSUE THREAD

**Issue by Jiaming1999** [pustotnik/zenmake#43] opened 2021-10-22 00:57 UTC
Assertion of return code is not correct when running pytest:
```
cd tests
pytest func_taskfeature_test.py
```
receive error message
=================================================== short test summary info =================================================== 
FAILED func_taskfeature_test.py::TestFeatureRunCmd::testBasis[normal-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureRunCmd::testBasis[zipapp-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildBTNoRTNone[normal-cpp\09-complex-unittest] - assert 1 == 0        
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildBTNoRTNone[zipapp-cpp\09-complex-unittest] - assert 1 == 0        
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildBTYesRTNone[normal-cpp\09-complex-unittest] - assert 1 == 0       
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildBTYesRTNone[zipapp-cpp\09-complex-unittest] - assert 1 == 0       
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildRTAllVariants[normal-cpp\09-complex-unittest] - assert 1 == 0     
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdBuildRTAllVariants[zipapp-cpp\09-complex-unittest] - assert 1 == 0     
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTest[normal-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTest[zipapp-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestBTNoRTNone[normal-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestBTNoRTNone[zipapp-cpp\09-complex-unittest] - assert 1 == 0
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestBTYesRTNone[normal-cpp\09-complex-unittest] - assert 1 == 0        
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestBTYesRTNone[zipapp-cpp\09-complex-unittest] - assert 1 == 0        
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestRTAllVariants[normal-cpp\09-complex-unittest] - assert 1 == 0      
FAILED func_taskfeature_test.py::TestFeatureTest::testCmdTestRTAllVariants[zipapp-cpp\09-complex-unittest] - assert 1 == 0

**Comment by pustotnik** [comment] 2021-11-10 12:38
I cannot reproduce the problem.
Moreover you did not provide any extra information. No OS, version of python, pytest, zenmake, etc.
I don't know what to do with your report.

**Comment by pustotnik** [comment] 2021-11-14 07:05
Well, I have some words to say. All tests of zenmake are regularly run on Linux (Gentoo, Debian, Ubuntu), Windows 10 and MacOS 10.15. You can see the status of most of these runs here in github actions. In your case I can only guess what is wrong and I guess that you don't have all necessary dependencies for tests. You can read about such dependencies here: [demos/README.rst](https://github.com/pustotnik/zenmake/blob/master/demos/README.rst).
For example if you run these tests on MacOS without clang compiler then these tests will fail. I think you will see the real reason of failure if you run tests as `pytest -v func_taskfeature_test.py`.

I close this issue.

**Closed by pustotnik** 2021-11-14 07:05 UTC

**Comment by Jiaming1999** [comment] 2021-11-14 23:02
> Well, I have some words to say. All tests of zenmake are regularly run on Linux (Gentoo, Debian, Ubuntu), Windows 10 and MacOS 10.15. You can see the status of most of these runs here in github actions. In your case I can only guess what is wrong and I guess that you don't have all necessary dependencies for tests. You can read about such dependencies here: [demos/README.rst](https://github.com/pustotnik/zenmake/blob/master/demos/README.rst). For example if you run these tests on MacOS without clang compiler then these tests will fail. I think you will see the real reason of failure if you run tests as `pytest -v func_taskfeature_test.py`.
> 
> I close this issue.

OK, I ran those tests on Win10. I will re-try to set up the dependencies and run. Thanks for the tip.

**Comment by pustotnik** [comment] 2021-11-15 03:12
Here are results from Win10 in KVM:

```
C:\Files\zenmake\tests>pytest func_taskfeature_test.py
================================================= test session starts =================================================
platform win32 -- Python 3.7.2, pytest-5.3.5, py-1.8.0, pluggy-0.12.0
==================================================
= System information =
CPU name: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
CPU architecture: AMD64
Number of CPUs: 2
Bit architecture: 64bit
Platform: windows
Platform id string: Windows-10-10.0.19041-SP0
Operating system: windows
Distro:
Python version: 3.7.2
Python implementation: CPython
--------------------
Detected toolchains:
GCC: gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
CLANG: clang version 8.0.1 (tags/RELEASE_801/final)
MSVC: 15.9
DMD: not recognized
LDC: not recognized
GDC: not recognized
GFORTRAN: GNU Fortran (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
IFORT: not recognized
==================================================

rootdir: C:\Files\zenmake\tests
plugins: cov-2.8.1, forked-1.1.3, mock-2.0.0, xdist-1.23.2
collected 18 items

func_taskfeature_test.py ..................                                                                      [100%]

=========================================== 18 passed in 108.73s (0:01:48) ============================================
```

Full list of installed extra packages with choco:

```
choco list --localonly
Chocolatey v0.10.15
boost-msvc-14.1 1.67.0
chocolatey 0.10.15
chocolatey-core.extension 1.3.3
chocolatey-visualstudio.extension 1.8.1
chocolatey-windowsupdate.extension 1.0.4
dotnetfx 4.7.2.20180712
git 2.22.0
git.install 2.22.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
ldc 1.20.0
llvm 8.0.1
mc 4.8.21.209
microsoft-build-tools 15.0.26320.2
mingw 8.1.0
pip 1.2.0
python 3.7.2
python3 3.7.2
vcredist140 14.22.27821
vcredist2017 14.16.27033
visualstudio-installer 2.0.1
visualstudio2017-workload-vctools 1.3.2
visualstudio2017buildtools 15.9.11.0
26 packages installed.
```

But for tests that you ran I think it should be enough to install only microsoft-build-tools. Of cource it is only needed if you have not installed MSVC already.
